### User Requests

GET http://localhost:3201/api/v1/users

###

POST http://localhost:3201/api/v1/users 
Content-Type: application/json

{
"username": "Greg", 
"password": "password"
}

### Log in Requests


POST http://localhost:3201/users/login
Content-Type: application/json

{
"username": "Greg", 
"password": "mypassword"
}

### Submission Requests
GET http://localhost:3201/submissions

###

POST http://localhost:3201/submissions
Content-Type: application/json

{ 
    "id":  1,
    "user_id": 1,
    "isCorrect": false
}

